- name: "Rat Guide"
  website: "http://www.ratguide.com"
- name: "The Rat Fan Club"
  website: "http://www.ratfanclub.org"
- name: "RatsRule"
  website: "http://www.ratsrule.com"
- name: "Suebee's Rat Diet"
  website: "http://www.ratsrule.com/diet.html"
- name: "Rat & Mouse Club of America"
  website: "http://www.rmca.org"
- name: "Rat Biology and Behaviour"
  website: "http://www.ratbehavior.org"
- name: "Join Rats"
  website: "http://www.joinrats.com"
- name: "Exotic Pets"
  website: "http://www.exoticpets.about.com"
- name: "Rat Assistance & Teaching Society"
  website: "http://www.petrats.org"
- name: "Martin's Cages"
  website: "http://www.martinscages.com/products/cages/rat/"
